# Generated by Django 4.2.7 on 2026-07-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
